import type { ShafiiRule } from "../engine/models";

/**
 * ═══════════════════════════════════════════════════════════════════
 *  CENTRAL SHAFI‘I RULE CONFIGURATION — المذهب الشافعي
 * ───────────────────────────────────────────────────────────────────
 *  Every inheritance rule the engine applies lives here, with its id,
 *  conditions, result, classical references and verification status.
 *  The UI never contains rules; scholars/developers edit this file.
 *
 *  Statuses:
 *   VERIFIED       — attested classical Shafi'i position, cited.
 *   PENDING_REVIEW — implemented from standard Shafi'i summaries but
 *                    awaiting line-by-line scholar verification.
 *   NEEDS_REVISION — flagged for correction.
 *
 *  A PENDING_REVIEW rule is never represented to users as religiously
 *  verified. Final review by a qualified scholar of Faraid is required
 *  before production use.
 * ═══════════════════════════════════════════════════════════════════
 */
export const SHAFII_MADHHAB = {
  ar: "المذهب الشافعي",
  en: "Shafi‘i Madhhab",
  ml: "ശാഫിഈ മദ്ഹബ്",
} as const;

const QURAN_4_11 = { source: "القرآن الكريم", location: "سورة النساء: 11" };
const QURAN_4_12 = { source: "القرآن الكريم", location: "سورة النساء: 12" };
const QURAN_4_176 = { source: "القرآن الكريم", location: "سورة النساء: 176" };
const MINHAJ = { source: "منهاج الطالبين — الإمام النووي", location: "كتاب الفرائض" };
const MUGHNI = { source: "مغني المحتاج — الخطيب الشربيني", location: "كتاب الفرائض" };
const TUHFA = { source: "تحفة المحتاج — ابن حجر الهيتمي", location: "كتاب الفرائض" };

export const inheritanceRules: ShafiiRule[] = [
  // ───────────────────────── ELIGIBILITY ─────────────────────────
  {
    id: "R-ELIG-SPOUSE-01",
    madhhab: "shafii",
    category: "ELIGIBILITY",
    description: {
      ar: "الزوج يرث فقط إذا كان المتوفى أنثى، والزوجة فقط إذا كان المتوفى ذكرًا.",
      en: "A husband inherits only from a female deceased; a wife only from a male deceased.",
      ml: "ഭർത്താവ് സ്ത്രീ മരിച്ചാൽ മാത്രം; ഭാര്യ പുരുഷൻ മരിച്ചാൽ മാത്രം.",
    },
    conditions: { ar: "تحديد جنس المتوفى", en: "Deceased gender is known" },
    result: { ar: "استبعاد الزوج/الزوجة غير المطابق لجنس المتوفى", en: "Non-matching spouse excluded" },
    priority: 100,
    references: [MINHAJ],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-ELIG-WIVES-01",
    madhhab: "shafii",
    category: "ELIGIBILITY",
    description: {
      ar: "حدّ الزوجات الوارثات أربع.",
      en: "At most four wives may inherit.",
      ml: "പരമാവധി നാല് ഭാര്യമാർ.",
    },
    conditions: { ar: "عدد الزوجات المدخل", en: "Number of wives entered" },
    result: { ar: "رفض أكثر من أربع زوجات", en: "More than four wives rejected" },
    priority: 100,
    references: [QURAN_4_12, MINHAJ],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-ELIG-ARHAM-01",
    madhhab: "shafii",
    category: "ELIGIBILITY",
    description: {
      ar: "الجدّ لأم من ذوي الأرحام، والصحيح في مذهب الشافعي أن ذوي الأرحام لا يرثون؛ فالباقي لبيت المال.",
      en: "The maternal grandfather is a dhawu al-arham; the established Shafi'i position is that dhawu al-arham do not inherit — the residue goes to the bayt al-mal.",
      ml: "മാതൃപിതാമഹൻ ദുൽഅർഹാം വിഭാഗമാണ്; ശാഫിഈ മദ്ഹബിൽ അവർക്ക് അനന്തരാവകാശമില്ല — ബാക്കി ബൈത്തുൽ മാലിന്.",
    },
    conditions: { ar: "وجود الجد لأم", en: "Maternal grandfather present" },
    result: { ar: "لا يرث — الباقي لبيت المال", en: "Does not inherit — residue to bayt al-mal" },
    priority: 95,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },

  // ───────────────────────── HAJB — الحجب ─────────────────────────
  {
    id: "R-HAJB-SON-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "الابن يحجب: ابن الابن وبنت الابن (حجب حرمان)، والإخوة الأشقاء والإخوة لأب.",
      en: "A son completely blocks: the son's son, the son's daughter, full brothers and paternal half-brothers.",
      ml: "മകൻ: പൗത്രൻ, പൗത്രി, സഹോദരൻ, പിതൃസഹോദരൻ എന്നിവരെ തടയുന്നു.",
    },
    conditions: { ar: "وجود ابن", en: "Son present" },
    result: { ar: "حجب حرمان للمذكورين", en: "Complete exclusion (hajb hirman)" },
    priority: 90,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-HAJB-SONSSON-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "ابن الابن (عند عدم الابن) يحجب الإخوة الأشقاء والإخوة لأب.",
      en: "The son's son (when no son exists) blocks full brothers and paternal half-brothers.",
      ml: "മകനില്ലെങ്കിൽ പൗത്രൻ സഹോദരന്മാരെ തടയുന്നു.",
    },
    conditions: { ar: "وجود ابن ابن وعدم الابن", en: "Son's son present, no son" },
    result: { ar: "حجب الإخوة الأشقاء ولأب", en: "Full/paternal brothers blocked" },
    priority: 89,
    references: [MINHAJ],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-HAJB-DESC-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "أي ولد أو ولد ابن (ذكرًا أو أنثى) يحجب الإخوة لأم.",
      en: "Any descendant (child or child of a son, male or female) blocks maternal half-siblings.",
      ml: "ഏതെങ്കിലും സന്തതി മാതൃസഹോദരങ്ങളെ തടയുന്നു.",
    },
    conditions: { ar: "وجود فرع وارث", en: "Any inheriting descendant" },
    result: { ar: "حجب الإخوة لأم", en: "Maternal siblings blocked" },
    priority: 88,
    references: [QURAN_4_12, MINHAJ],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-HAJB-FATHER-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "الأب يحجب جميع الإخوة (أشقاء ولأب ولأم) والجدات.",
      en: "The father blocks all siblings (full, paternal and maternal) and the grandmothers.",
      ml: "പിതാവ് എല്ലാ സഹോദരങ്ങളെയും മുത്തശ്ശിമാരെയും തടയുന്നു.",
    },
    conditions: { ar: "وجود الأب", en: "Father present" },
    result: { ar: "حجب حرمان للإخوة والجدات", en: "Siblings and grandmothers blocked" },
    priority: 87,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-HAJB-GRANDFATHER-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "الجدّ الصحيح (أبو الأب) يحجب الإخوة جميعًا عند الإمام الشافعي؛ لأنه يُنزَّل منزلة الأب في الأصح.",
      en: "The paternal grandfather blocks all siblings in the Shafi'i school, since he stands in the father's place (the established position).",
      ml: "പിതൃപിതാമഹൻ എല്ലാ സഹോദരങ്ങളെയും തടയുന്നു (ശാഫിഈ നിലപാട്).",
    },
    conditions: { ar: "وجود الجد وعدم الأب", en: "Grandfather present, no father" },
    result: { ar: "حجب الإخوة", en: "Siblings blocked" },
    priority: 86,
    references: [MINHAJ, TUHFA],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-HAJB-MOTHER-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "الأم تحجب الجدات (لأب ولأم).",
      en: "The mother blocks both paternal and maternal grandmothers.",
      ml: "മാതാവ് മുത്തശ്ശിമാരെ തടയുന്നു.",
    },
    conditions: { ar: "وجود الأم", en: "Mother present" },
    result: { ar: "حجب الجدات", en: "Grandmothers blocked" },
    priority: 85,
    references: [MINHAJ],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-HAJB-FULLBRO-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "الأخ الشقيق يحجب الأخ لأب والأخت لأب.",
      en: "A full brother blocks paternal half-brothers and paternal half-sisters.",
      ml: "സഹോദരൻ പിതൃസഹോദരങ്ങളെ തടയുന്നു.",
    },
    conditions: { ar: "وجود أخ شقيق غير محجوب", en: "Unblocked full brother present" },
    result: { ar: "حجب الإخوة والأخوات لأب", en: "Paternal half-siblings blocked" },
    priority: 80,
    references: [MINHAJ],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-HAJB-FULLSIS-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "الأختان الشقيقتان فأكثر تحجبان الأخت لأب إلا أن يكون معها أخ لأب يعصّبها.",
      en: "Two or more full sisters block the paternal half-sister unless a paternal half-brother makes her a residuary.",
      ml: "രണ്ടോ അതിലധികമോ സഹോദരിമാർ പിതൃസഹോദരിയെ തടയുന്നു (പിതൃസഹോദരൻ ഉണ്ടെങ്കിൽ ഒഴിവാകും).",
    },
    conditions: { ar: "أختان شقيقتان فأكثر دون أخ لأب", en: "≥2 full sisters, no paternal half-brother" },
    result: { ar: "حجب الأخت لأب", en: "Paternal half-sister blocked" },
    priority: 79,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-HAJB-DAUGHTERS-01",
    madhhab: "shafii",
    category: "HAJB",
    description: {
      ar: "البنتان فأكثر تحجبان بنت الابن إلا أن يكون معها ابن ابن يعصّبها.",
      en: "Two or more daughters block the son's daughter unless a son's son makes her a residuary.",
      ml: "രണ്ടോ അതിലധികമോ പെൺമക്കൾ പൗത്രിയെ തടയുന്നു (പൗത്രൻ ഉണ്ടെങ്കിൽ ഒഴിവാകും).",
    },
    conditions: { ar: "بنتان فأكثر دون ابن ابن", en: "≥2 daughters, no son's son" },
    result: { ar: "حجب بنت الابن", en: "Son's daughter blocked" },
    priority: 78,
    references: [MINHAJ],
    verificationStatus: "VERIFIED",
  },

  // ───────────────────────── FURUD — أصحاب الفروض ─────────────────────────
  {
    id: "R-FURUD-HUSBAND-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للزوج النصف عند عدم الفرع الوارث.",
      en: "The husband receives 1/2 when the deceased has no inheriting descendant.",
      ml: "സന്തതിയില്ലെങ്കിൽ ഭർത്താവിന് പകുതി.",
    },
    conditions: { ar: "عدم الفرع الوارث", en: "No inheriting descendant" },
    result: { ar: "1/2", en: "1/2" },
    priority: 70,
    references: [QURAN_4_12],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-HUSBAND-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للزوج الربع مع الفرع الوارث.",
      en: "The husband receives 1/4 when the deceased has an inheriting descendant.",
      ml: "സന്തതി ഉണ്ടെങ്കിൽ ഭർത്താവിന് കാൽഭാഗം.",
    },
    conditions: { ar: "وجود الفرع الوارث", en: "Inheriting descendant exists" },
    result: { ar: "1/4", en: "1/4" },
    priority: 70,
    references: [QURAN_4_12],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-WIFE-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للزوجة الربع عند عدم الفرع الوارث، ويقسمنه بينهن بالتساوي.",
      en: "The wife (wives, shared equally) receives 1/4 when there is no inheriting descendant.",
      ml: "സന്തതിയില്ലെങ്കിൽ ഭാര്യ(മാർ)ക്ക് കാൽഭാഗം — തുല്യമായി പങ്കിടും.",
    },
    conditions: { ar: "عدم الفرع الوارث", en: "No inheriting descendant" },
    result: { ar: "1/4", en: "1/4 (shared)" },
    priority: 70,
    references: [QURAN_4_12],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-WIFE-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للزوجة الثمن مع الفرع الوارث، ويقسمنه بينهن بالتساوي.",
      en: "The wife (wives, shared equally) receives 1/8 when there is an inheriting descendant.",
      ml: "സന്തതി ഉണ്ടെങ്കിൽ ഭാര്യ(മാർ)ക്ക് എട്ടിൽ ഒന്ന് — തുല്യമായി പങ്കിടും.",
    },
    conditions: { ar: "وجود الفرع الوارث", en: "Inheriting descendant exists" },
    result: { ar: "1/8", en: "1/8 (shared)" },
    priority: 70,
    references: [QURAN_4_12],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-DAUGHTER-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للبنت الواحدة النصف عند عدم الابن.",
      en: "A single daughter receives 1/2 when there is no son.",
      ml: "ഒറ്റപ്പെൺമകൾക്ക് മകനില്ലെങ്കിൽ പകുതി.",
    },
    conditions: { ar: "بنت واحدة وعدم الابن", en: "One daughter, no son" },
    result: { ar: "1/2", en: "1/2" },
    priority: 69,
    references: [QURAN_4_11],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-DAUGHTER-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للبنتين فأكثر الثلثان عند عدم الابن.",
      en: "Two or more daughters receive 2/3 when there is no son.",
      ml: "രണ്ടോ അതിലധികമോ പെൺമക്കൾക്ക് മകനില്ലെങ്കിൽ മൂന്നിൽ രണ്ട്.",
    },
    conditions: { ar: "بنتان فأكثر وعدم الابن", en: "≥2 daughters, no son" },
    result: { ar: "2/3", en: "2/3 (shared)" },
    priority: 69,
    references: [QURAN_4_11],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-DAUGHTER-03",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "البنت مع الابن عصبة بالغير: للذكر مثل حظ الأنثيين.",
      en: "Daughters with a son become residuaries (asabah bi-ghayrihi): the male receives twice the female's portion.",
      ml: "മകനൊപ്പം പെൺമക്കൾ അസബ ബിൽഗൈർ: ആൺ-പെൺ അനുപാതം 2:1.",
    },
    conditions: { ar: "اجتماع الابن والبنت", en: "Son(s) and daughter(s) together" },
    result: { ar: "تعصيب: للذكر ضعف الأنثى", en: "Residue, male = 2× female" },
    priority: 69,
    references: [QURAN_4_11],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-SONSDAUGHTER-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "بنت الابن تأخذ النصف منفردة أو الثلثين متعددات عند عدم الابن والبنت وابن الابن.",
      en: "The son's daughter takes 1/2 alone or 2/3 if several, absent son, daughter and son's son.",
      ml: "പൗത്രിക്ക് (മകൻ/പെൺമകൾ/പൗത്രൻ ഇല്ലെങ്കിൽ) പകുതി അല്ലെങ്കിൽ മൂന്നിൽ രണ്ട്.",
    },
    conditions: { ar: "عدم الابن والبنت وابن الابن", en: "No son, daughter or son's son" },
    result: { ar: "1/2 أو 2/3", en: "1/2 or 2/3" },
    priority: 68,
    references: [MINHAJ],
    verificationStatus: "PENDING_REVIEW",
  },
  {
    id: "R-FURUD-SONSDAUGHTER-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "لبنت الابن السدس تكملة الثلثين مع البنت الواحدة وعدم ابن الابن.",
      en: "The son's daughter receives 1/6 to complete the two-thirds when there is exactly one daughter and no son's son.",
      ml: "ഒരേയൊരു പെൺമകളുണ്ടെങ്കിൽ പൗത്രിക്ക് മൂന്നിൽ രണ്ട് തികയ്ക്കാൻ ആറിലൊന്ന്.",
    },
    conditions: { ar: "بنت واحدة + بنت ابن وعدم ابن وابن ابن", en: "One daughter + son's daughter, no son/son's son" },
    result: { ar: "1/6 تكملة", en: "1/6 complement" },
    priority: 68,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "PENDING_REVIEW",
  },
  {
    id: "R-FURUD-FATHER-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للأب السدس مع الفرع الوارث المذكر.",
      en: "The father receives 1/6 when there is a male inheriting descendant.",
      ml: "ആൺ സന്തതി ഉണ്ടെങ്കിൽ പിതാവിന് ആറിലൊന്ന്.",
    },
    conditions: { ar: "فرع وارث مذكر", en: "Male inheriting descendant" },
    result: { ar: "1/6", en: "1/6" },
    priority: 67,
    references: [QURAN_4_11],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-FATHER-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للأب السدس والباقي مع الفرع الوارث المؤنث فقط.",
      en: "The father receives 1/6 plus the residue when there are only female inheriting descendants.",
      ml: "പെൺ സന്തതികൾ മാത്രമുള്ളപ്പോൾ പിതാവിന് ആറിലൊന്നും ബാക്കിയും.",
    },
    conditions: { ar: "فرع مؤنث فقط", en: "Only female descendants" },
    result: { ar: "1/6 + الباقي", en: "1/6 + residue" },
    priority: 67,
    references: [QURAN_4_11, MINHAJ],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-FATHER-03",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "الأب عصبة بنفسه عند عدم الفرع الوارث فيأخذ الباقي.",
      en: "With no inheriting descendant, the father is a residuary (asabah bi-nafsihi) and takes the remainder.",
      ml: "സന്തതിയില്ലെങ്കിൽ പിതാവ് അസബ — ബാക്കി മുഴുവൻ.",
    },
    conditions: { ar: "عدم الفرع الوارث", en: "No inheriting descendant" },
    result: { ar: "الباقي تعصيبًا", en: "Residue" },
    priority: 67,
    references: [QURAN_4_11],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-GRANDFATHER-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "الجدّ الصحيح (أبو الأب) يُنزَّل منزلة الأب عند عدمه في الأصح من مذهب الشافعي: يرث ميراثه ويحجب الإخوة.",
      en: "The paternal grandfather stands in the father's place when the father is absent (the established Shafi'i position): he inherits as the father would and blocks siblings.",
      ml: "പിതാവ് ഇല്ലെങ്കിൽ പിതൃപിതാമഹൻ പിതാവിന്റെ സ്ഥാനത്ത് (ശാഫിഈ നിലപാട്).",
    },
    conditions: { ar: "وجود الجد وعدم الأب", en: "Grandfather present, father absent" },
    result: { ar: "حُكم الأب", en: "Father's ruling" },
    priority: 66,
    references: [MINHAJ, TUHFA],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-MOTHER-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للأم السدس مع الفرع الوارث.",
      en: "The mother receives 1/6 when there is an inheriting descendant.",
      ml: "സന്തതി ഉണ്ടെങ്കിൽ മാതാവിന് ആറിലൊന്ന്.",
    },
    conditions: { ar: "وجود الفرع الوارث", en: "Inheriting descendant exists" },
    result: { ar: "1/6", en: "1/6" },
    priority: 65,
    references: [QURAN_4_11],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-MOTHER-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للأم السدس مع العدد من الإخوة (اثنين فأكثر من أي نوع).",
      en: "The mother receives 1/6 when there are two or more siblings of any kind.",
      ml: "രണ്ടോ അതിലധികമോ സഹോദരങ്ങളുണ്ടെങ്കിൽ മാതാവിന് ആറിലൊന്ന്.",
    },
    conditions: { ar: "إخوة اثنان فأكثر", en: "Two or more siblings" },
    result: { ar: "1/6", en: "1/6" },
    priority: 65,
    references: [QURAN_4_11],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-MOTHER-03",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للأم الثلث عند عدم الفرع الوارث وعدم العدد من الإخوة.",
      en: "The mother receives 1/3 when there is no descendant and fewer than two siblings.",
      ml: "സന്തതിയും രണ്ട് സഹോദരങ്ങളും ഇല്ലെങ്കിൽ മാതാവിന് മൂന്നിലൊന്ന്.",
    },
    conditions: { ar: "عدم الفرع والعدد من الإخوة", en: "No descendant, <2 siblings" },
    result: { ar: "1/3", en: "1/3" },
    priority: 65,
    references: [QURAN_4_11],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-UMARI-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "المسألة العمرية (زوج + أبوان): للزوج النصف وللام ثلث الباقي والباقي للأب.",
      en: "Umariyyah case (husband + both parents): husband 1/2, mother 1/3 of the remainder, father the residue.",
      ml: "ഉമരിയ്യ കേസ് (ഭർത്താവ് + മാതാപിതാക്കൾ): ഭർത്താവ് 1/2, മാതാവ് ബാക്കിയുടെ 1/3, പിതാവ് ബാക്കി.",
    },
    conditions: { ar: "زوج وأم وأب فقط", en: "Only husband, mother and father" },
    result: { ar: "1/2، ثلث الباقي، الباقي", en: "1/2, 1/3 of remainder, residue" },
    priority: 64,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-UMARI-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "المسألة العمرية (زوجة + أبوان): للزوجة الربع وللام ثلث الباقي والباقي للأب.",
      en: "Umariyyah case (wife + both parents): wife 1/4, mother 1/3 of the remainder, father the residue.",
      ml: "ഉമരിയ്യ കേസ് (ഭാര്യ + മാതാപിതാക്കൾ): ഭാര്യ 1/4, മാതാവ് ബാക്കിയുടെ 1/3, പിതാവ് ബാക്കി.",
    },
    conditions: { ar: "زوجة وأم وأب فقط", en: "Only wife, mother and father" },
    result: { ar: "1/4، ثلث الباقي، الباقي", en: "1/4, 1/3 of remainder, residue" },
    priority: 64,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-GRANDMOTHER-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للجدات السدس يقسمنه بينهن بالتساوي (صحيحات الجدات).",
      en: "Grandmothers share 1/6 equally.",
      ml: "മുത്തശ്ശിമാർ ആറിലൊന്ന് തുല്യമായി പങ്കിടുന്നു.",
    },
    conditions: { ar: "جدة فأكثر غير محجوبة", en: "One or more unblocked grandmothers" },
    result: { ar: "1/6 بالتساوي", en: "1/6 equally" },
    priority: 63,
    references: [MINHAJ],
    verificationStatus: "PENDING_REVIEW",
  },
  {
    id: "R-FURUD-FULLSIS-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للأخت الشقيقة النصف منفردة والثلثان متعددات عند عدم المعصّب والحاجب.",
      en: "A full sister takes 1/2 alone or 2/3 if several, absent a male residuary or blocker.",
      ml: "സഹോദരിക്ക് പകുതി അല്ലെങ്കിൽ മൂന്നിൽ രണ്ട് (തടസ്സമില്ലെങ്കിൽ).",
    },
    conditions: { ar: "عدم الابن وابن الابن والأب والجد والأخ الشقيق", en: "No son, son's son, father, grandfather or full brother" },
    result: { ar: "1/2 أو 2/3", en: "1/2 or 2/3" },
    priority: 62,
    references: [QURAN_4_176],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-FULLSIS-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "الأخت الشقيقة مع أخيها الشقيق عصبة بالغير: للذكر مثل حظ الأنثيين.",
      en: "Full sisters with full brothers become residuaries: male = 2× female.",
      ml: "സഹോദരനൊപ്പം സഹോദരി അസബ ബിൽഗൈർ (2:1).",
    },
    conditions: { ar: "اجتماع الأخ والأخت الشقيقين", en: "Full brother(s) with full sister(s)" },
    result: { ar: "تعصيب 2:1", en: "Residue 2:1" },
    priority: 62,
    references: [QURAN_4_176],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-PATSIS-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للأخت لأب النصف أو الثلثان كالشقيقة عند عدمها، والسدس تكملة الثلثين مع الشقيقة الواحدة.",
      en: "A paternal half-sister takes 1/2 or 2/3 like the full sister when there is none, or 1/6 as complement with exactly one full sister.",
      ml: "പിതൃസഹോദരിക്ക് പകുതി/മൂന്നിൽ രണ്ട്; ഒരു സഹോദരിക്കൊപ്പം ആറിലൊന്ന് (തികയ്ക്കാൻ).",
    },
    conditions: { ar: "عدم الشقيقة أو شقيقة واحدة", en: "No full sister, or exactly one" },
    result: { ar: "1/2 أو 2/3 أو 1/6", en: "1/2, 2/3 or 1/6" },
    priority: 61,
    references: [QURAN_4_176, MINHAJ],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-MATSIB-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للأخ/الأخت لأم السدس منفردًا.",
      en: "A single maternal half-sibling receives 1/6.",
      ml: "ഒറ്റ മാതൃസഹോദരത്തിന് ആറിലൊന്ന്.",
    },
    conditions: { ar: "واحد لأم وعدم الحاجب", en: "One maternal sibling, no blocker" },
    result: { ar: "1/6", en: "1/6" },
    priority: 60,
    references: [QURAN_4_12],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-FURUD-MATSIB-02",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "للإخوة لأم الثلث عند التعدد، يقسمنه بالتساوي الذكر والأنثى سواء.",
      en: "Two or more maternal half-siblings share 1/3 equally, male and female alike.",
      ml: "രണ്ടോ അതിലധികമോ മാതൃസഹോദരങ്ങൾ മൂന്നിലൊന്ന് തുല്യമായി പങ്കിടുന്നു.",
    },
    conditions: { ar: "اثنان فأكثر لأم", en: "Two or more maternal siblings" },
    result: { ar: "1/3 بالتساوي", en: "1/3 equally" },
    priority: 60,
    references: [QURAN_4_12],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-MUSHTARAKAH-01",
    madhhab: "shafii",
    category: "FURUD",
    description: {
      ar: "المسألة المشتركة (الحجرية): زوج وأم أو جدة وإخوة لأم اثنان فأكثر وإخوة أشقاء — يشترك الإخوة لأم والأشقاء في الثلث بالسوية. هذا معتمد المذهب الشافعي.",
      en: "Mushtarakah case: husband + mother (or grandmother) + ≥2 maternal siblings + full brothers — maternal siblings and full brothers share the 1/3 equally. This is the relied-upon Shafi'i position.",
      ml: "മുഷ്തറക കേസ്: മാതൃസഹോദരങ്ങളും സഹോദരന്മാരും മൂന്നിലൊന്ന് തുല്യമായി പങ്കിടുന്നു (ശാഫിഈ നിലപാട്).",
    },
    conditions: {
      ar: "زوج + أم/جدة + إخوة لأم ≥2 + أخ شقيق فأكثر دون إخوة لأب أو فرع",
      en: "Husband + mother/grandmother + ≥2 maternal siblings + full brother(s), no paternal siblings or descendants",
    },
    result: { ar: "الثلث مشترك بالسوية", en: "1/3 shared equally" },
    priority: 59,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "PENDING_REVIEW",
  },

  // ───────────────────────── ASABAH — العصبة ─────────────────────────
  {
    id: "R-ASABAH-ORDER-01",
    madhhab: "shafii",
    category: "ASABAH",
    description: {
      ar: "ترتيب العصبات بالنفس: الابن ثم ابن الابن ثم الأب/الجد ثم الأخ الشقيق ثم الأخ لأب — الأقرب فالأقرب.",
      en: "Order of residuaries in their own right: son, then son's son, then father/grandfather, then full brother, then paternal half-brother — nearest first.",
      ml: "അസബ ക്രമം: മകൻ, പൗത്രൻ, പിതാവ്/പിതാമഹൻ, സഹോദരൻ, പിതൃസഹോദരൻ.",
    },
    conditions: { ar: "وجود باقٍ بعد الفروض", en: "Residue exists after fixed shares" },
    result: { ar: "الباقي لأقرب عصبة", en: "Residue to the nearest residuary class" },
    priority: 50,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-ASABAH-2TO1-01",
    madhhab: "shafii",
    category: "ASABAH",
    description: {
      ar: "في العصبة بالغير (الابن مع البنت، وابن الابن مع بنت الابن، والأخ مع الأخت) يقسم الباقي للذكر مثل حظ الأنثيين.",
      en: "Within a residuary pair (son/daughter, son's son/son's daughter, brother/sister) the residue is divided male = 2× female. Applied only where the verified rule requires it.",
      ml: "അസബ ജോഡികളിൽ ബാക്കി 2:1 അനുപാതത്തിൽ.",
    },
    conditions: { ar: "عصبة بالغير", en: "Residuary pair present" },
    result: { ar: "للذكر ضعف الأنثى", en: "Male = 2× female" },
    priority: 50,
    references: [QURAN_4_11, QURAN_4_176],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-ASABAH-MAGHAYR-01",
    madhhab: "shafii",
    category: "ASABAH",
    description: {
      ar: "الأخت الشقيقة (ثم الأخت لأب عند عدمها) مع البنت أو بنت الابن تصير عصبة مع الغير فتأخذ الباقي.",
      en: "A full sister (then a paternal half-sister if none) with a daughter or son's daughter becomes a residuary (asabah ma‘a al-ghayr) and takes the remainder.",
      ml: "പെൺമകളോടൊപ്പം സഹോദരി അസബ മഅൽ ഗൈർ — ബാക്കി അവൾക്ക്.",
    },
    conditions: { ar: "أخت غير محجوبة + بنت/بنت ابن وعدم العصبة بالنفس", en: "Unblocked sister + female descendant, no male residuary" },
    result: { ar: "الباقي للأخت", en: "Residue to the sister" },
    priority: 49,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },

  // ───────────────────────── AWL — العول ─────────────────────────
  {
    id: "R-AWL-01",
    madhhab: "shafii",
    category: "AWL",
    description: {
      ar: "إذا زادت الفروض على التركة عالت المسألة: تُقسم التركة على مجموع السهام ويأخذ كل صاحب فرض سهمه من المجموع الجديد — والزوجان يعولان معاملةً بالمساواة.",
      en: "When the fixed shares exceed the estate, the base is increased (awl): each fixed heir's share is scaled proportionally; spouses participate in awl.",
      ml: "ഓഹരികൾ ആകെത്തുകയിൽ കൂടിയാൽ അവൽ പ്രയോഗിക്കും — എല്ലാവരുടെയും ഓഹരി ആനുപാതികമായി കുറയും.",
    },
    conditions: { ar: "مجموع الفروض > 1", en: "Sum of fixed shares > 1" },
    result: { ar: "تخفيض نسبي لجميع الفروض", en: "Proportional reduction of all fixed shares" },
    priority: 40,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },

  // ───────────────────────── RADD — الرد ─────────────────────────
  {
    id: "R-RADD-01",
    madhhab: "shafii",
    category: "RADD",
    description: {
      ar: "إذا بقي فائض بعد الفروض ولا عصبة، يُردّ الفائض على أصحاب الفروض — عدا الزوجين في الأصح من مذهب الشافعي — بنسبة فروضهم.",
      en: "If a residue remains with no residuary, it is returned (radd) to the fixed heirs — excluding the spouses in the established Shafi'i position — in proportion to their shares.",
      ml: "ബാക്കി തുക അസബ ഇല്ലെങ്കിൽ നിശ്ചിത ഓഹരിക്കാർക്ക് (ഇണകൾ ഒഴികെ — ശാഫിഈ നിലപാട്) ആനുപാതികമായി മടങ്ങും.",
    },
    conditions: { ar: "فائض > 0 وعدم العصبة", en: "Residue > 0 and no residuary" },
    result: { ar: "ردّ نسبي عدا الزوجين", en: "Proportional return, spouses excluded" },
    priority: 39,
    references: [MINHAJ, TUHFA],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-RADD-02",
    madhhab: "shafii",
    category: "RADD",
    description: {
      ar: "لا يُردّ على الزوجين في الأصح؛ فإن بقي فائض بعد فرضهما ولا مستحق له فالباقي لبيت المال.",
      en: "Spouses do not receive radd (established position); if a residue remains after the spouse's share with no other heir, it goes to the bayt al-mal.",
      ml: "ഇണകൾക്ക് റദ് ഇല്ല; മറ്റാരുമില്ലെങ്കിൽ ബാക്കി ബൈത്തുൽ മാലിന്.",
    },
    conditions: { ar: "فائض بعد فرض الزوج وعدم وارث آخر", en: "Residue after spouse's share, no other heir" },
    result: { ar: "الباقي لبيت المال", en: "Residue to bayt al-mal" },
    priority: 38,
    references: [MINHAJ, MUGHNI],
    verificationStatus: "VERIFIED",
  },
  {
    id: "R-BAYT-01",
    madhhab: "shafii",
    category: "BAYT_AL_MAL",
    description: {
      ar: "عند عدم الورثة أصلًا أو عدم مستحق للرد، يكون المال (أو الباقي) لبيت المال في مذهب الشافعي.",
      en: "When there are no heirs at all, or none entitled to radd, the estate (or remainder) goes to the bayt al-mal in the Shafi'i school.",
      ml: "അവകാശികൾ ഇല്ലെങ്കിൽ മുഴുവനും ബൈത്തുൽ മാലിന്.",
    },
    conditions: { ar: "عدم الوارث", en: "No inheriting heir" },
    result: { ar: "المال لبيت المال", en: "Estate to bayt al-mal" },
    priority: 37,
    references: [MINHAJ],
    verificationStatus: "VERIFIED",
  },
];

export function getRule(id: string): ShafiiRule | undefined {
  return inheritanceRules.find((r) => r.id === id);
}
